version: '3.7'

services:
  pokerback:
    build:
      context: ../../pokerback
      dockerfile: docker/Dockerfile
    command: ./manage.py runserver 0.0.0.0:8000
    volumes:
      - ../../pokerback/:/app
    ports:
      - 8000:8000
    env_file:
      - ../envs/dev/.env.dev
    environment:
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis
  db:
    image: postgres:12.0
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=pokerback
      - POSTGRES_PASSWORD=pokerback
      - POSTGRES_DB=pokerback_dev
    ports:
      - 9628:5432
  redis:
    image: redis:3.2-alpine
    command: redis-server
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379

volumes:
  postgres_data:
  redis_data: