# Generated by Django 3.0.7 on 2020-08-15 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoomModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_uuid", models.UUIDField(db_index=True)),
                ("room_key", models.CharField(db_index=True, max_length=16)),
                (
                    "game_type",
                    models.CharField(choices=[("POKER", "poker")], max_length=64),
                ),
                (
                    "room_status",
                    models.CharField(
                        choices=[("ACTIVE", "active"), ("CLOSED", "closed")],
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("closed_at", models.DateTimeField(null=True)),
                (
                    "host_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="host_user",
                        to="user.User",
                    ),
                ),
            ],
        ),
    ]
